\documentclass[12pt,preprint, authoryear]{elsarticle}

\usepackage{lmodern}
%%%% My spacing
\usepackage{setspace}
\setstretch{1.2}
\DeclareMathSizes{12}{14}{10}{10}

% Wrap around which gives all figures included the [H] command, or places it "here". This can be tedious to code in Rmarkdown.
\usepackage{float}
\let\origfigure\figure
\let\endorigfigure\endfigure
\renewenvironment{figure}[1][2] {
    \expandafter\origfigure\expandafter[H]
} {
    \endorigfigure
}

\let\origtable\table
\let\endorigtable\endtable
\renewenvironment{table}[1][2] {
    \expandafter\origtable\expandafter[H]
} {
    \endorigtable
}


\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
    \usepackage{xltxtra,xunicode}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi

\usepackage{amssymb, amsmath, amsthm, amsfonts}

\def\bibsection{\section*{References}} %%% Make "References" appear before bibliography


\usepackage[round]{natbib}

\usepackage{longtable}
\usepackage[margin=2.3cm,bottom=2cm,top=2.5cm, includefoot]{geometry}
\usepackage{fancyhdr}
\usepackage[bottom, hang, flushmargin]{footmisc}
\usepackage{graphicx}
\numberwithin{equation}{section}
\numberwithin{figure}{section}
\numberwithin{table}{section}
\setlength{\parindent}{0cm}
\setlength{\parskip}{1.3ex plus 0.5ex minus 0.3ex}
\usepackage{textcomp}
\renewcommand{\headrulewidth}{0pt}

\usepackage{array}
\newcolumntype{x}[1]{>{\centering\arraybackslash\hspace{0pt}}p{#1}}

%%%%  Remove the "preprint submitted to" part. Don't worry about this either, it just looks better without it:
\makeatletter
\def\ps@pprintTitle{%
  \let\@oddhead\@empty
  \let\@evenhead\@empty
  \let\@oddfoot\@empty
  \let\@evenfoot\@oddfoot
}
\makeatother

 \def\tightlist{} % This allows for subbullets!

\usepackage{hyperref}
\hypersetup{breaklinks=true,
            bookmarks=true,
            colorlinks=true,
            citecolor=blue,
            urlcolor=blue,
            linkcolor=blue,
            pdfborder={0 0 0}}


% The following packages allow huxtable to work:
\usepackage{siunitx}
\usepackage{multirow}
\usepackage{hhline}
\usepackage{calc}
\usepackage{tabularx}
\usepackage{booktabs}
\usepackage{caption}


\newenvironment{columns}[1][]{}{}

\newenvironment{column}[1]{\begin{minipage}{#1}\ignorespaces}{%
\end{minipage}
\ifhmode\unskip\fi
\aftergroup\useignorespacesandallpars}

\def\useignorespacesandallpars#1\ignorespaces\fi{%
#1\fi\ignorespacesandallpars}

\makeatletter
\def\ignorespacesandallpars{%
  \@ifnextchar\par
    {\expandafter\ignorespacesandallpars\@gobble}%
    {}%
}
\makeatother

\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newenvironment{CSLReferences}%
  {\setlength{\parindent}{0pt}%
  \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces}%
  {\par}


\urlstyle{same}  % don't use monospace font for urls
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\setcounter{secnumdepth}{5}

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}

%%% Include extra packages specified by user
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

%%% Hard setting column skips for reports - this ensures greater consistency and control over the length settings in the document.
%% page layout
%% paragraphs
\setlength{\baselineskip}{12pt plus 0pt minus 0pt}
\setlength{\parskip}{12pt plus 0pt minus 0pt}
\setlength{\parindent}{0pt plus 0pt minus 0pt}
%% floats
\setlength{\floatsep}{12pt plus 0 pt minus 0pt}
\setlength{\textfloatsep}{20pt plus 0pt minus 0pt}
\setlength{\intextsep}{14pt plus 0pt minus 0pt}
\setlength{\dbltextfloatsep}{20pt plus 0pt minus 0pt}
\setlength{\dblfloatsep}{14pt plus 0pt minus 0pt}
%% maths
\setlength{\abovedisplayskip}{12pt plus 0pt minus 0pt}
\setlength{\belowdisplayskip}{12pt plus 0pt minus 0pt}
%% lists
\setlength{\topsep}{10pt plus 0pt minus 0pt}
\setlength{\partopsep}{3pt plus 0pt minus 0pt}
\setlength{\itemsep}{5pt plus 0pt minus 0pt}
\setlength{\labelsep}{8mm plus 0mm minus 0mm}
\setlength{\parsep}{\the\parskip}
\setlength{\listparindent}{\the\parindent}
%% verbatim
\setlength{\fboxsep}{5pt plus 0pt minus 0pt}



\begin{document}



\begin{frontmatter}  %

\title{A Historical Analysis of the Olympic Games}

% Set to FALSE if wanting to remove title (for submission)




\author[Add1]{Annika Pretorius (21626979)\footnote{\textbf{Contributions:}
  \newline \emph{The author would like to thank my viewers in New
  Dehli.}}}
\ead{}





\address[Add1]{Stellenbosch University}


\begin{abstract}
\small{
This article aims to discuss interesting historical facts regarding the
Summer and Winter Olympics, backed by evidence
}
\end{abstract}

\vspace{1cm}





\vspace{0.5cm}

\end{frontmatter}



%________________________
% Header and Footers
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\pagestyle{fancy}
\chead{}
\rhead{}
\lfoot{}
\rfoot{}
\lhead{}
%\rfoot{\footnotesize Page \thepage } % "e.g. Page 2"
\cfoot{}

%\setlength\headheight{30pt}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%________________________

\headsep 35pt % So that header does not go over title




\hypertarget{analysing-the-total-metals-won-by-india-and-other-countries}{%
\section{Analysing the Total Metals Won by India and other
Countries}\label{analysing-the-total-metals-won-by-india-and-other-countries}}

\begingroup\fontsize{11pt}{12pt}\selectfont
\begin{longtable}{lrrrr}
\caption{Total Medals by Country \label{tab:total_medals}} \\ 
  \toprule
Country & Bronze & Gold & Silver & Total\_Medals \\ 
  \midrule
Argentina &  28 &  18 &  24 &  70 \\ 
  Brazil &  55 &  23 &  29 & 107 \\ 
  Chile &   4 &   2 &   7 &  13 \\ 
  China & 119 & 170 & 141 & 430 \\ 
  Colombia &  11 &   2 &   6 &  19 \\ 
  India &  11 &   9 &   6 &  26 \\ 
  Indonesia &  11 &   5 &  11 &  27 \\ 
  Mexico &  27 &  13 &  20 &  60 \\ 
  Nigeria &  12 &   2 &   9 &  23 \\ 
  Peru &   0 &   1 &   3 &   4 \\ 
  Russia & 138 & 125 & 113 & 376 \\ 
  South Africa &  27 &  23 &  26 &  76 \\ 
  Turkey &  23 &  38 &  25 &  86 \\ 
  Uruguay &   6 &   2 &   2 &  10 \\ 
   \bottomrule
\end{longtable}
\endgroup

\begin{itemize}
\item
  The Table \ref{tab:total_medals} above presents a comprehensive
  analysis of the total medals won by India and other selected countries
  in the Olympics. China leads the chart with an impressive 430 total
  medals, comprising 170 gold, 141 silver, and 119 bronze medals,
  reflecting its dominance in the global sporting arena. Russia follows
  with 376 total medals, including 125 gold, 113 silver, and 138 bronze
  medals, showcasing its strong performance in various sports
  disciplines.
\item
  Other notable performances include Brazil and South Africa, which have
  secured 107 and 76 total medals, respectively. Brazil's medal tally is
  highlighted by 23 gold, 29 silver, and 55 bronze medals, while South
  Africa has 23 gold, 26 silver, and 27 bronze medals.
\item
  India, the focal point of this analysis, has won a total of 26 medals,
  with 9 gold, 6 silver, and 11 bronze medals. This places India behind
  several countries in the table, indicating room for improvement in its
  Olympic performance.
\item
  Overall, the data underscores the varying levels of success among
  different countries, with China and Russia emerging as top contenders,
  while countries like India and Nigeria exhibit potential for growth
  and development in their Olympic pursuits.
\end{itemize}

\hypertarget{analysing-the-top-countries-dominating-both-the-summer-and-winter-olympics-over-the-years-a-time-series-analysis}{%
\section{Analysing the Top Countries Dominating both the Summer and
Winter Olympics over the Years: A Time-Series
Analysis}\label{analysing-the-top-countries-dominating-both-the-summer-and-winter-olympics-over-the-years-a-time-series-analysis}}

\hypertarget{analysis-of-total-medals-over-the-years}{%
\subsection{Analysis of Total Medals Over the
Years}\label{analysis-of-total-medals-over-the-years}}

\begin{itemize}
\tightlist
\item
  The plot displays the total number of medals won by the top 5
  countries (GER, SWE, URS, USA) over the years.
\item
  The data spans from the early 1900s to 2010, showing fluctuations in
  medal counts for each country.
\item
  The Soviet Union (URS) exhibits a significant peak in medals won
  around the 1980s, indicating a period of dominance in the Olympics.
\item
  The United States (USA) consistently maintains high medal counts
  throughout the years, with noticeable peaks and troughs.
\item
  Germany (GER) shows an upward trend in medal counts post-1950s, while
  Sweden (SWE) remains relatively stable with lower medal counts
  compared to other countries. +The plot highlights the changing
  dynamics and competitive landscape of the Olympics, with different
  countries emerging as dominant forces in different time periods.
\end{itemize}

\begin{figure}

{\centering \includegraphics{README_files/figure-latex/unnamed-chunk-1-1} 

}

\caption{The Top Countries that Dominate in both the Summer and Winter Olympics\label{Figure1}}\label{fig:unnamed-chunk-1}
\end{figure}

\hypertarget{the-most-unlikely-top-countries-as-per-gdp-per-capita-or-by-population}{%
\section{The Most Unlikely Top Countries as per GDP Per Capita or by
Population}\label{the-most-unlikely-top-countries-as-per-gdp-per-capita-or-by-population}}

\textbf{Top 5 Countries by Medals Per Capita}:

\begin{itemize}
\item
  \textbf{URS (Union of Soviet Socialist Republics)}: Stands out
  significantly, indicating that the country had a high medal count
  relative to its population size.
\item
  \textbf{GDR (German Democratic Republic)}: Also shows a strong
  performance, punching above its weight in terms of population size.
  East Germany, officially known as the German Democratic Republic, was
  a country in Central Europe from its formation on 7 October 1949 until
  its reunification with West Germany on 3 October 1990.
\item
  \textbf{ROU (Romania)}: Shows a commendable number of medals won per
  capita.
\item
  \textbf{FRG (Federal Republic of Germany)}: Consistently performs well
  in the Olympic Games, and is referencing West Germany. West
  Germany{[}a{]} is the common English name for the Federal Republic of
  Germany (FRG){[}b{]} from its formation on 23 May 1949 until the
  reunification with East Germany on 3 October 1990.
\item
  \textbf{TCH (Czechoslovakia)}: Displays strong performance relative to
  its population.
\end{itemize}

\begin{figure}

{\centering \includegraphics{README_files/figure-latex/unnamed-chunk-2-1} 

}

\caption{The Top Countries that Dominate Winning Medals Per Capita\label{Figure2}}\label{fig:unnamed-chunk-2}
\end{figure}

\textbf{Top 5 Countries by Medals Per GDP}:

\begin{itemize}
\item
  \textbf{URS (Union of Soviet Socialist Republics)}: Again leads,
  showing exceptional performance relative to its economic size.
\item
  \textbf{GDR (German Democratic Republic)}: Demonstrates effective use
  of economic resources in achieving Olympic success.
\item
  \textbf{ROU (Romania)}: Efficiently converts its economic resources
  into medals.
\item
  \textbf{FRG (Federal Republic of Germany)}: Maintains a strong
  position in terms of medals per GDP.
\item
  \textbf{CUB (Cuba)}: Punches above its weight economically in terms of
  Olympic success.
\end{itemize}

\begin{figure}

{\centering \includegraphics{README_files/figure-latex/unnamed-chunk-3-1} 

}

\caption{The Top Countries that Dominate Winning Medals Per Capita\label{Figure3}}\label{fig:unnamed-chunk-3}
\end{figure}

\textbf{Similarity in Figures}:

\begin{itemize}
\item
  The two figures show similar countries leading in both medals per
  capita and medals per GDP. This similarity suggests that these
  countries not only excel in their ability to convert population size
  into Olympic success but also manage their economic resources
  efficiently to achieve high medal counts.
\item
  The dominance of URS and GDR in both figures highlights their
  historical strength in Olympic competitions during the periods they
  existed, indicating state-sponsored sports programs and a high
  prioritization of athletic success.
\item
  Countries like Romania (ROU) and the Federal Republic of Germany (FRG)
  demonstrate consistent performance, reflecting well-organized sports
  programs that effectively harness both population and economic
  resources.
\end{itemize}

\hypertarget{an-analysis-of-archery}{%
\section{An Analysis of Archery}\label{an-analysis-of-archery}}

\begin{itemize}
\item
  Archery's history at the Olympic Games is split into two periods: the
  early era and the modern era.
\item
  The sport featured on the programme of the Olympic Games in 1900,
  1904, 1908 and 1920 during the early era. It was also one of the first
  sports to feature women's events, in 1904. The competition formats
  were inconsistent, often based on local rules, and archery was
  subsequently dropped from the programme. World Archery was founded in
  1931 with the goal of rejoining the Games.
\item
  Archery returned to the Olympic Games in 1972 and has remained on the
  programme ever since. During this modern era, the competition format
  has evolved toward exciting, easily accessible and broadcast-friendly
  head-to-head matchplay. Two gold medals, for the individual events,
  were awarded from 1972 to 1984; team events were added in 1988.
\end{itemize}

\begin{figure}

{\centering \includegraphics{README_files/figure-latex/unnamed-chunk-4-1} 

}

\caption{The Top Individual Events by Country in Winning Medals in Archery\label{Figure4}}\label{fig:unnamed-chunk-4}
\end{figure}

\hypertarget{list-of-countries-in-the-figure-above}{%
\subsection{List of Countries in the Figure
above}\label{list-of-countries-in-the-figure-above}}

\begin{itemize}
\tightlist
\item
  AUS: Australia
\item
  CHN: China
\item
  EUN: Unified Team
\item
  FIN: Finland
\item
  FRA: France
\item
  GBR: Great Britain
\item
  ITA: Italy
\item
  JPN: Japan
\item
  KOR: South Korea
\item
  MEX: Mexico
\item
  NED: Netherlands
\item
  POL: Poland
\item
  RUS: Russia
\item
  SWE: Sweden
\item
  UKR: Ukraine
\item
  URS: Union of Soviet Socialist Republics
\item
  USA: United States
\end{itemize}

\begin{figure}

{\centering \includegraphics{README_files/figure-latex/unnamed-chunk-5-1} 

}

\caption{A Pie Chart showcasing the Distibution of Medal Winnings by the Top 5 Countries in Individual Archery Events\label{Figure5}}\label{fig:unnamed-chunk-5}
\end{figure}

\begin{itemize}
\tightlist
\item
  The pie chart above shows the medal distribution by the top 5
  countries in Archery individual events between the years 1900 and
  2012. South Korea (KOR) dominates the chart with 46.7\% of the total
  medals, followed by the USA (20\%), the Soviet Union (URS) with
  15.6\%, Japan (JPN) with 8.9\%, and China (CHN) with 8.9\%.
\end{itemize}

\hypertarget{analysing-the-performance-in-individual-archery-events-by-gender}{%
\subsection{Analysing the Performance in Individual Archery Events by
Gender}\label{analysing-the-performance-in-individual-archery-events-by-gender}}

\begin{itemize}
\item
  The multi-panel plot compares the performance in Archery individual
  events by gender within the top 5 countries (China, Finland, Japan,
  South Korea, Soviet Union, and the USA) from 1970 to 2010.
\item
  Each panel represents one of the top countries, showing the total
  medals won by men and women over the years.
\item
  South Korea (KOR) and the USA display noticeable differences in
  performance between genders, while other countries like China,
  Finland, and Japan show consistent performance between men and women.
\end{itemize}

\begin{figure}

{\centering \includegraphics{README_files/figure-latex/unnamed-chunk-6-1} 

}

\caption{The Top Countries that Dominate in both the Summer and Winter Olympics\label{Figure6}}\label{fig:unnamed-chunk-6}
\end{figure}

\begin{verbatim}
## # A tibble: 2 x 5
##   term        estimate std.error statistic p.value
##   <chr>          <dbl>     <dbl>     <dbl>   <dbl>
## 1 (Intercept)   -0.167     0.410    -0.408   0.683
## 2 GenderWomen   -0.325     0.561    -0.580   0.562
\end{verbatim}

\begin{figure}

{\centering \includegraphics{README_files/figure-latex/unnamed-chunk-7-1} 

}

\caption{The Top Countries that Dominate in both the Summer and Winter Olympics\label{Figure7}}\label{fig:unnamed-chunk-7}
\end{figure}

\begin{itemize}
\item
  Finally, \ref{Figure7}, determines if there is a correlation between
  gender and the probability of winning a medal by fitted a logistic
  regression model.
\item
  This model helped us predict the probability of winning a gold medal
  based on gender.
\item
  The x-axis represents the gender (Men and Women).
\item
  The y-axis represents the predicted probability of winning a gold
  medal.
\item
  Each dot represents a predicted probability from the logistic
  regression model.
\item
  The predicted probabilities for men are clustered around 0.46, while
  for women, they are around 0.38. This indicates that, historically,
  men have had a higher probability of winning gold medals in Archery
  individual events compared to women within the top 10 countries.
\end{itemize}

\bibliography{Tex/ref}





\end{document}
